const assert = require('assert');
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const appJson = JSON.parse(fs.readFileSync(path.join(root, 'miniprogram/app.json'), 'utf8'));
const adminJs = fs.readFileSync(path.join(root, 'miniprogram/pages/admin/index.js'), 'utf8');
const adminWxml = fs.readFileSync(path.join(root, 'miniprogram/pages/admin/index.wxml'), 'utf8');
const adminWxss = fs.readFileSync(path.join(root, 'miniprogram/pages/admin/index.wxss'), 'utf8');

assert.ok(appJson.pages.includes('pages/admin/index'));
assert.match(adminWxml, /Pro 管理后台/);
assert.match(adminWxml, /批量生成兑换码/);
assert.match(adminWxml, /运营健康面板/);
assert.match(adminWxml, /云端暂存/);
assert.match(adminWxml, /绑定转化漏斗/);
assert.match(adminWxml, /初步判断/);
assert.match(adminWxml, /内容类型/);
assert.match(adminWxml, /需要关注的问题/);
assert.match(adminWxml, /兑换码列表/);
assert.match(adminWxml, /Pro 用户列表/);
assert.match(adminWxml, /绑定码列表/);
assert.match(adminWxml, /管理密钥/);
assert.match(adminJs, /adminGenerateRedeemCodes/);
assert.match(adminJs, /adminListRedeemCodes/);
assert.match(adminJs, /adminListEntitlements/);
assert.match(adminJs, /adminListBindCodes/);
assert.match(adminJs, /adminGetDashboard/);
assert.match(adminJs, /loadDashboard/);
assert.match(adminJs, /maxRead: 5000/);
assert.match(adminJs, /adminUpdateEntitlement/);
assert.match(adminJs, /adminUpdateRedeemCode/);
assert.match(adminJs, /markRedeemCodeSent/);
assert.match(adminJs, /markRedeemCodeUnsent/);
assert.match(adminJs, /deliveryStatusText/);
assert.match(adminWxml, /markRedeemCodeSent/);
assert.match(adminWxml, /markRedeemCodeUnsent/);
assert.match(adminJs, /wx\.setClipboardData/);
assert.match(adminWxss, /\.admin-page/);
assert.match(adminWxss, /\.metric-grid/);
assert.match(adminWxss, /\.dashboard-columns/);
assert.match(adminWxss, /\.funnel-box/);
assert.match(adminWxss, /\.diagnosis-item/);
assert.match(adminWxss, /\.code-grid/);
