const assert = require('assert');
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'admin-console/index.html'), 'utf8');
const js = fs.readFileSync(path.join(root, 'admin-console/app.js'), 'utf8');
const css = fs.readFileSync(path.join(root, 'admin-console/styles.css'), 'utf8');
const adminApi = fs.readFileSync(path.join(root, 'cloudfunctions/adminApi/index.js'), 'utf8');
const syncAdminHandler = fs.readFileSync(path.join(root, 'cloudfunctions/syncApi/admin-handler.js'), 'utf8');
const packageJson = JSON.parse(fs.readFileSync(path.join(root, 'cloudfunctions/adminApi/package.json'), 'utf8'));

assert.strictEqual(packageJson.name, 'admin-api');
assert.match(html, /overviewView/);
assert.match(html, /funnelView/);
assert.match(html, /proView/);
assert.match(html, /proTable/);
assert.match(html, /expiredProTable/);
assert.match(html, /availableCodeTable/);
assert.match(html, /paymentOrderTable/);
assert.match(html, /paymentOrderCountText/);
assert.doesNotMatch(html, /usedOrInvalidCodeTable/);
assert.doesNotMatch(html, /usedOrInvalidCodeCountText/);
assert.match(html, /<details class="collapsible-panel" open>/);
assert.match(html, /<summary class="panel-summary">/);
assert.doesNotMatch(html, /data-view="users"/);
assert.doesNotMatch(html, /data-view="codes"/);
assert.doesNotMatch(html, /data-view="bindings"/);
assert.doesNotMatch(html, /id="usersView"/);
assert.doesNotMatch(html, /id="codesView"/);
assert.doesNotMatch(html, /id="bindingsView"/);
assert.match(html, /apiBase/);
assert.match(html, /adminSecret/);
assert.match(html, /rangeTabs/);
assert.match(html, /codeStatusFilter/);
assert.match(html, /codeDeliveryFilter/);
assert.match(html, /cloudCreditMinutes/);
assert.doesNotMatch(html, /codeRedemptions/);
assert.match(js, /\/summary/);
assert.match(js, /\/admin\$\{path\}/);
assert.match(js, /loadFunnel/);
assert.match(js, /loadCurrentView/);
assert.match(js, /loadedViews/);
assert.match(js, /renderBreakpoints/);
assert.match(js, /renderSegments/);
assert.match(js, /renderTrends/);
assert.doesNotMatch(js, /loadUsers/);
assert.doesNotMatch(js, /loadBindings/);
assert.doesNotMatch(js, /refreshUsers/);
assert.doesNotMatch(js, /refreshBindings/);
assert.match(js, /\/pro-users/);
assert.match(js, /activeProUsers/);
assert.match(js, /expiredProUsers/);
assert.match(js, /availableRedeemCodes/);
assert.doesNotMatch(js, /usedOrInvalidRedeemCodes/);
assert.doesNotMatch(js, /usedOrInvalidCodeTable/);
assert.doesNotMatch(js, /boundDeviceCount/);
assert.doesNotMatch(js, /bindCodeCount/);
assert.match(js, /buildRedeemCodeMap/);
assert.match(js, /allCodeData/);
assert.match(js, /request\('\/redeem-codes', \{ keyword: '', limit: 500, maxRead: 5000 \}\)/);
assert.match(js, /redeemedCount/);
assert.match(js, /lastRedeemedOpenId/);
assert.doesNotMatch(js, /codeRedemptions/);
assert.doesNotMatch(js, /maxRedemptions:\s*Number/);
assert.match(js, /redeemedAt/);
assert.match(js, /formatMinutes/);
assert.match(js, /cloudUsedSeconds/);
assert.match(js, /cloudQuotaSeconds/);
assert.match(js, /cloudRemainingSeconds/);
assert.match(js, /\/redeem-codes/);
assert.match(js, /\/redeem-codes\/generate/);
assert.match(js, /\/redeem-codes\/update/);
assert.match(js, /\/entitlements\/update/);
assert.match(js, /\/payment-orders/);
assert.match(js, /\/payment-orders\/update/);
assert.match(js, /renderPaymentOrders/);
assert.doesNotMatch(js, /\/bind-codes/);
assert.match(js, /localStorage/);
assert.match(js, /x-admin-secret/);
assert.match(js, /data-entitlement-action="extend"/);
assert.match(js, /data-entitlement-action="addCloudQuota"/);
assert.match(js, /cloudCreditMinutes/);
assert.match(js, /data-code-action="markSent"/);
assert.match(js, /data-code-action="disable"/);
assert.match(js, /loadProManagement/);
assert.match(js, /codeStatusFilter/);
assert.match(js, /codeDeliveryFilter/);
assert.doesNotMatch(js, /expired'\s*\)\s*:\s*`<span class="tag warn">\$?\{?escapeHtml\(user\.proStatus/);

assert.match(css, /\.sidebar/);
assert.match(css, /\.metric-grid/);
assert.match(css, /\.funnel-list/);
assert.match(css, /\.breakpoint-list/);
assert.match(css, /\.segment-grid/);
assert.match(css, /\.trend-list/);
assert.match(css, /\.table-wrap/);
assert.match(css, /\.collapsible-panel/);
assert.match(css, /\.panel-summary/);

assert.match(adminApi, /REDEEM_ADMIN_SECRET/);
assert.match(adminApi, /summarizeAdminDashboard/);
assert.match(adminApi, /buildUserRows/);
assert.match(adminApi, /listProUsers/);
assert.match(adminApi, /cloudQuotaSeconds/);
assert.match(adminApi, /cloudUsedSeconds/);
assert.match(adminApi, /cloudRemainingSeconds/);
assert.match(adminApi, /listRecords/);
assert.match(adminApi, /generateRedeemCodes/);
assert.match(adminApi, /updateEntitlement/);
assert.match(adminApi, /listPaymentOrders/);
assert.match(adminApi, /updatePaymentOrder/);
assert.match(adminApi, /\/records/);
assert.match(adminApi, /buildRecordDiagnosticRow/);
assert.match(adminApi, /access-control-allow-origin/);
assert.match(syncAdminHandler, /listRecords/);
assert.match(syncAdminHandler, /\/records/);
assert.match(syncAdminHandler, /buildRecordDiagnosticRow/);
assert.match(syncAdminHandler, /cloudRemainingSeconds/);
assert.match(syncAdminHandler, /addCloudQuota/);
assert.match(syncAdminHandler, /cloudQuotaSeconds/);
assert.match(syncAdminHandler, /listPaymentOrders/);
assert.match(syncAdminHandler, /updatePaymentOrder/);
