'use strict';
const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),os=require('os'),http=require('http'),crypto=require('crypto'),cp=require('child_process'),Module=require('module');
const root=path.resolve(__dirname,'..'),installer=path.join(root,'obsidian-plugin/wechat-inbox-sync/local-asr/install-local-asr.ps1');
const source=fs.readFileSync(installer,'utf8');const metadataInit=source.slice(source.indexOf('$script:DownloadEvents ='),source.indexOf('$NativeProcessRunnerVersion'));
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'asr-resume-test-'));
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const body=crypto.randomBytes(1024*1024),digest=hash(body),requests=[];let mode='normal',dropped=false;
const server=http.createServer((req,res)=>{const start=Number((req.headers.range||'').match(/bytes=(\d+)-/)?.[1]||0);requests.push({start,path:req.url});
 if(mode==='forbidden'){res.writeHead(403);return res.end();}
 if(mode==='timeout'){res.writeHead(start?206:200,{'Content-Length':body.length-start,...(start?{'Content-Range':`bytes ${start}-${body.length-1}/${body.length}`}:{})});res.write(body.subarray(start,start+65536));return;}
 if(mode==='complete-close'){res.writeHead(200,{'Transfer-Encoding':'chunked'});res.write(body);setTimeout(()=>res.destroy(),80);return;}
 const ranged=Boolean(req.headers.range)&&mode!=='no-range';const payload=mode==='corrupt'?Buffer.alloc(body.length,99):body;
 res.writeHead(ranged?206:200,{'Content-Length':payload.length-(ranged?start:0),...(ranged?{'Content-Range':`bytes ${start}-${payload.length-1}/${payload.length}`}:{})});
 if(mode==='drop'&&!dropped){dropped=true;res.write(payload.subarray(start,start+131072));setTimeout(()=>res.destroy(),80);return;}
 res.end(payload.subarray(ranged?start:0));
});
function psQuote(v){return "'"+String(v).replace(/'/g,"''")+"'";}
function run(script){return new Promise((resolve,reject)=>{cp.execFile('powershell.exe',['-NoProfile','-NonInteractive','-EncodedCommand',Buffer.from(script,'utf16le').toString('base64')],{windowsHide:true,timeout:18000,maxBuffer:1024*1024},(error,stdout,stderr)=>resolve({code:error?.code||0,stdout,stderr}));});}
function scaffold(dir,url,extra='') {return `$ErrorActionPreference='Stop'\n$InstallRoot=${psQuote(dir)}\n$env:WECHAT_INBOX_ASR_DOWNLOAD_ASSETS=${psQuote(JSON.stringify(Array.from({length:4},(_,i)=>({url:url+(i?'-other-'+i:''),sha256:digest,byteLength:body.length+i}))))}\n${metadataInit}\n$DownloadLowSpeedLimitBytesPerSecond=65536\n$DownloadLowSpeedTimeoutSeconds=30\n$DownloadTimeoutSeconds=5\n$t=$null;$e=$null;$ast=[System.Management.Automation.Language.Parser]::ParseFile(${psQuote(installer)},[ref]$t,[ref]$e)\nif($e.Count){throw ($e|Out-String)}\n$names=@('Get-DownloadSpec','Write-DownloadStatus','Preserve-UnverifiedDownload','Test-DownloadComplete','Download-File','Install-ModelPackage','Assert-DownloadedFile','Get-EnabledAssetUrls')\n$ast.FindAll({param($n) $n -is [System.Management.Automation.Language.FunctionDefinitionAst] -and $names -contains $n.Name},$false) | ForEach-Object {Invoke-Expression $_.Extent.Text}\n${extra}`;}
function partial(dir,bytes=131072,identity=hash('sha256:'+digest)){fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'model.bin'),body.subarray(0,bytes));fs.writeFileSync(path.join(dir,'model.bin.download.json'),JSON.stringify({identity}));}
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}/model.bin`;let checks=0;
const execute=async(name,extra='',targetUrl=url)=>{const dir=path.join(tmp,name);fs.mkdirSync(dir,{recursive:true});const script=scaffold(dir,url,extra+`\nDownload-File -Url ${psQuote(targetUrl)} -OutFile (Join-Path $InstallRoot 'model.bin') -Resume`);return {dir,...await run(script)};};
mode='drop';let r=await execute('drop');assert.equal(r.code,0,r.stderr);assert.equal(hash(fs.readFileSync(path.join(r.dir,'model.bin'))),digest);assert.deepEqual(requests.map(x=>x.start),[0,131072]);checks++;
requests.length=0;mode='normal';r=await execute('drop','',url+'?sign=secret-refreshed');assert.equal(r.code,0,r.stderr);assert.equal(requests.length,0,'verified cache must not redownload after signed URL refresh');assert.ok(!fs.readFileSync(path.join(r.dir,'download-status.json'),'utf8').includes('secret'));checks++;
const resume=path.join(tmp,'cross-run');partial(resume);mode='forbidden';requests.length=0;r=await execute('cross-run');assert.notEqual(r.code,0);assert.equal(requests.length,1);assert.equal(fs.statSync(path.join(resume,'model.bin')).size,131072);mode='normal';requests.length=0;r=await execute('cross-run','',url+'?sign=renewed');assert.equal(r.code,0,r.stderr);assert.equal(requests[0].start,131072);checks++;
const wrong=path.join(tmp,'wrong-full');partial(wrong,body.length);fs.writeFileSync(path.join(wrong,'model.bin'),Buffer.alloc(body.length));requests.length=0;r=await execute('wrong-full');assert.equal(r.code,0,r.stderr);assert.equal(requests[0].start,0);assert.ok(fs.readdirSync(wrong).some(n=>n.includes('.unverified-')));assert.equal(hash(fs.readFileSync(path.join(wrong,'model.bin'))),digest);checks++;
const unknown=path.join(tmp,'unknown');partial(unknown,131072,'other-asset');requests.length=0;r=await execute('unknown');assert.equal(r.code,0,r.stderr);assert.equal(requests[0].start,0);assert.ok(fs.readdirSync(unknown).some(n=>n.includes('.unverified-')));checks++;
const noRange=path.join(tmp,'no-range');partial(noRange);mode='no-range';requests.length=0;r=await execute('no-range');assert.notEqual(r.code,0);assert.equal(requests.length,1);assert.equal(hash(fs.readFileSync(path.join(noRange,'model.bin'))),hash(body.subarray(0,131072)));checks++;
mode='complete-close';requests.length=0;r=await execute('complete-close');assert.equal(r.code,0,r.stderr);assert.equal(requests.length,1);assert.equal(hash(fs.readFileSync(path.join(r.dir,'model.bin'))),digest);checks++;
mode='corrupt';requests.length=0;r=await execute('bad-server');assert.notEqual(r.code,0);assert.equal(requests.length,1);assert.equal(fs.existsSync(path.join(r.dir,'model.bin')),false);assert.ok(fs.readFileSync(path.join(r.dir,'download-status.json'),'utf8').includes('integrity-failed'));checks++;
mode='normal';const modelDir=path.join(tmp,'model-min');partial(modelDir);requests.length=0;r=await run(scaffold(modelDir,url,`Install-ModelPackage -Urls @(${psQuote(url)}) -OutFile (Join-Path $InstallRoot 'model.bin') -MinBytes 16 -Label model | Out-Null`));assert.equal(r.code,0,r.stderr);assert.equal(requests[0].start,131072,'partial above old min size must be resumed and verified');checks++;
mode='timeout';requests.length=0;r=await execute('bounded-timeout','$DownloadTimeoutSeconds=1');assert.notEqual(r.code,0);assert.equal(requests.length,3);assert.ok(fs.statSync(path.join(r.dir,'model.bin')).size>0);checks++;
const priority=await run(scaffold(path.join(tmp,'priority'),url,`$urls=@(Get-EnabledAssetUrls -PrimaryUrls @('https://private.example/asset') -FallbackUrls @('https://github.com/slow')); if($urls.Count -ne 1 -or $urls[0] -ne 'https://private.example/asset'){throw 'priority failed'}`));assert.equal(priority.code,0,priority.stderr);checks++;
const orig=Module._load;Module._load=function(n,p,m){if(n==='obsidian')return{Plugin:class{},Modal:class{},PluginSettingTab:class{},Setting:class{},Notice:class{}};return orig.call(this,n,p,m)};const Plugin=require('../obsidian-plugin/wechat-inbox-sync/main.js');Module._load=orig;const h=Plugin.__test;
function plugin(platform='win32'){const p=new Plugin();p.ensureProFeatureAccess=async()=>({hasAccess:true});p.getActiveBindings=()=>[{token:'fixture'}];p.getConfiguredLocalAsrPlatform=()=>platform;return p;}
const asset={id:'model',fileName:'model.bin',sha256:digest,byteLength:body.length,downloadUrl:`https://${h.LOCAL_COMPONENT_DOWNLOAD_HOST}/local-components/by-sha256/${digest}/model.bin?sign=secret&t=1`};
const payload={success:true,data:{schemaVersion:2,deliveryProtocol:'cloudbase-v1',component:'asr',platform:'win32',arch:'x64',version:'test',expiresAt:new Date(Date.now()+600000).toISOString(),assets:[asset,...['ffmpeg','whisper','whisper-compat'].map(id=>({...asset,id,fileName:id+'.bin',downloadUrl:asset.downloadUrl.replaceAll('model.bin',id+'.bin')}))]}};
let p=plugin(),calls=0;p.requestJson=async()=>{if(++calls===1)throw Object.assign(Error('synthetic'),{code:'ECONNRESET'});return payload};assert.equal((await p.getAuthorizedLocalComponentManifest('asr')).assets.length,4);assert.equal(calls,2);checks++;
p=plugin();calls=0;p.requestJson=async()=>{calls++;throw Object.assign(Error('synthetic'),{code:'SERVER_UNAVAILABLE'})};await assert.rejects(p.getAuthorizedLocalComponentManifest('asr'),e=>e.code==='ASR_SOURCE_UNAVAILABLE');assert.equal(calls,2);checks++;
for(const missing of ['model','ffmpeg','whisper','whisper-compat']){p=plugin();calls=0;p.requestJson=async()=>{calls++;return {...payload,data:{...payload.data,assets:payload.data.assets.filter(a=>a.id!==missing)}}};await assert.rejects(p.getAuthorizedLocalComponentManifest('asr'),e=>e.code==='ASR_SOURCE_UNAVAILABLE');assert.equal(calls,2);checks++;}
p=plugin();calls=0;p.requestJson=async()=>{calls++;throw Object.assign(Error('denied'),{code:'PRO_REQUIRED',status:403})};await assert.rejects(p.getAuthorizedLocalComponentManifest('asr'),e=>e.code==='PRO_REQUIRED');assert.equal(calls,1);checks++;
p=plugin('darwin');calls=0;p.requestJson=async()=>{calls++;throw Error('synthetic')};assert.equal(await p.getAuthorizedLocalComponentManifest('asr'),null);assert.equal(calls,1);checks++;
const env=h.buildAuthorizedLocalComponentProcessEnv({},payload.data);assert.equal(env.WECHAT_INBOX_ASR_MODEL_URL,asset.downloadUrl);assert.ok(!env.WECHAT_INBOX_ASR_DOWNLOAD_ASSETS.includes('secret'));assert.equal(JSON.parse(env.WECHAT_INBOX_ASR_DOWNLOAD_ASSETS)[0].sha256,digest);checks++;
const diagnostic=path.join(tmp,'diag');fs.mkdirSync(diagnostic);fs.writeFileSync(path.join(diagnostic,'download-status.json'),JSON.stringify([{time:new Date().toISOString(),file:'model.bin',host:'safe.example',bytes:12,command:'PRIVATE TRANSCRIPT',url:'https://x?sign=secret',code:'SECRET WITH SPACES',unexpected:'secret'}]));const text=JSON.stringify(h.readLocalAsrDownloadDiagnostic(diagnostic));assert.ok(text.includes('model.bin'));assert.ok(!/secret|PRIVATE|command|unexpected/i.test(text));checks++;
console.log(`ASR resume: ${checks} behavioral cases passed (real Windows curl + local HTTP interruptions, cache integrity, manifest and diagnostic boundaries)`);
})().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>{server.closeAllConnections();server.close();if(!tmp.startsWith(path.join(os.tmpdir(),'asr-resume-test-')))throw Error('unsafe cleanup');fs.rmSync(tmp,{recursive:true,force:true})});
