const assert = require('assert');
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const wxml = fs.readFileSync(path.join(root, 'miniprogram/pages/index/index.wxml'), 'utf8');
const wxss = fs.readFileSync(path.join(root, 'miniprogram/pages/index/index.wxss'), 'utf8');
const js = fs.readFileSync(path.join(root, 'miniprogram/pages/index/index.js'), 'utf8');
const inboxServiceJs = fs.readFileSync(path.join(root, 'miniprogram/services/inbox-service.js'), 'utf8');
const appJson = JSON.parse(fs.readFileSync(path.join(root, 'miniprogram/app.json'), 'utf8'));
const projectConfig = JSON.parse(fs.readFileSync(path.join(root, 'project.config.json'), 'utf8'));
const appJs = fs.readFileSync(path.join(root, 'miniprogram/app.js'), 'utf8');
const proWxml = fs.readFileSync(path.join(root, 'miniprogram/pages/pro/index.wxml'), 'utf8');
const proJs = fs.readFileSync(path.join(root, 'miniprogram/pages/pro/index.js'), 'utf8');
const helpWxml = fs.readFileSync(path.join(root, 'miniprogram/pages/help/index.wxml'), 'utf8');
const helpJs = fs.readFileSync(path.join(root, 'miniprogram/pages/help/index.js'), 'utf8');

function listFiles(dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) return listFiles(fullPath);
    return [fullPath];
  });
}

const oversizedAssets = listFiles(path.join(root, 'miniprogram'))
  .filter((filePath) => /\.(png|jpe?g|gif|webp|svg|mp3|wav|m4a|aac)$/i.test(filePath))
  .map((filePath) => ({ filePath, size: fs.statSync(filePath).size }))
  .filter((item) => item.size > 200 * 1024);
assert.deepStrictEqual(oversizedAssets, []);

assert.deepStrictEqual(appJson.pages.slice(0, 3), [
  'pages/index/index',
  'pages/pro/index',
  'pages/admin/index',
]);
assert.ok(appJson.pages.includes('pages/help/index'));
assert.strictEqual(appJson.window.navigationBarTitleText, 'Obsidian 内容同步助手');
assert.strictEqual(appJson.supportedMaterials[0].desc, '保存公众号文章到 Obsidian 内容同步助手');
assert.ok(appJson.supportedMaterials.every((item) => String(item.name || '').includes('${nickname}')));
assert.ok(projectConfig.packOptions.ignore.some((item) => item.value === 'images/create_cbr.png'));
assert.ok(projectConfig.packOptions.ignore.some((item) => item.value === 'images/ai_example1.png'));

assert.match(wxml, /Obsidian 内容同步助手/);
assert.doesNotMatch(wxml, /把微信里的内容同步到 Obsidian/);
assert.doesNotMatch(wxml, /权限、教程和联系入口都放在这里。/);
assert.match(wxml, /currentView === 'collect'/);
assert.match(wxml, /currentView === 'bind'/);
assert.match(wxml, /currentView === 'mine'/);
assert.match(wxml, /class="tabbar"/);
assert.match(wxml, /data-view="collect"/);
assert.match(wxml, /data-view="bind"/);
assert.match(wxml, /data-view="mine"/);
assert.match(wxml, /绑定 Obsidian/);
assert.match(wxml, /开通 Pro/);
assert.match(wxml, /插件更新公告/);
assert.match(wxml, /最新插件版本：v\{\{pluginVersion\}\}/);
assert.match(wxml, /更新时间：\{\{pluginUpdatedAt\}\}/);
assert.match(wxml, /最近更新：\{\{announcementText\}\}/);
assert.match(wxml, /bindtap="showAnnouncementDetail"/);
assert.match(wxml, /class="usage-status/);
assert.match(wxml, /\{\{usageStatusText\}\}/);
assert.match(wxml, /wx:if="\{\{uploadProgressVisible\}\}"/);
assert.match(wxml, /class="upload-progress-card"/);
assert.match(wxml, /width:\{\{uploadProgressPercent\}\}%/);
assert.match(wxml, /\{\{uploadProgressText\}\}/);
assert.match(wxml, /现在支持以下网页/);
assert.match(wxml, /class="platform-compact-strip"/);
assert.match(wxml, /class="platform-compact-node free"/);
assert.match(wxml, /class="platform-compact-node pro"/);
assert.doesNotMatch(wxml, /class="platform-support-groups"/);
assert.doesNotMatch(wxml, /class="platform-support-group free"/);
assert.doesNotMatch(wxml, /class="platform-support-group pro"/);
assert.doesNotMatch(wxml, /class="platform-support-title"/);
assert.doesNotMatch(wxml, /class="platform-compact-row"/);
assert.doesNotMatch(wxml, /class="platform-mini-label free"/);
assert.doesNotMatch(wxml, /class="platform-mini-label pro"/);
assert.match(wxml, /图文免费，音视频 Pro/);
assert.match(wxml, /Pro 和免费版的权益对比/);
assert.match(wxml, /免费版/);
assert.match(wxml, /pro版/);
assert.match(wxml, /class="benefit-table"/);
assert.match(wxml, /class="benefit-table-header"/);
assert.match(wxml, /class="benefit-table-row"/);
assert.match(wxml, /使用次数/);
assert.match(wxml, /5次\/天/);
assert.match(wxml, /不限/);
assert.match(wxml, /文字、文件转写/);
assert.match(wxml, /语音、MP3转写/);
assert.match(wxml, /语音、MP3转写[\s\S]*<view class="benefit-cell">×<\/view>[\s\S]*<view class="benefit-cell pro-col">√<\/view>/);
assert.match(wxml, /图文链接转写/);
assert.match(wxml, /音视频链接转写/);
assert.match(wxml, /√/);
assert.match(wxml, /×/);
assert.doesNotMatch(wxml, /转写配置/);
assert.doesNotMatch(wxml, /适合场景/);
assert.match(wxml, /公众号/);
assert.match(wxml, /飞书/);
assert.match(wxml, /小红书/);
assert.match(wxml, /抖音/);
assert.match(wxml, /B站/);
assert.match(wxml, /小宇宙/);
assert.doesNotMatch(wxml, /class="platform-grid free-grid"/);
assert.doesNotMatch(wxml, /class="platform-grid pro-grid"/);
assert.doesNotMatch(wxml, /class="platform-node free"/);
assert.doesNotMatch(wxml, /class="platform-node pro"/);
assert.match(wxml, /class="platform-compact-node free"/);
assert.match(wxml, /class="platform-compact-node pro"/);
assert.match(wxml, /class="platform-logo-image"/);
assert.match(wxml, /images\/platforms\/wechat-article\.svg/);
assert.match(wxml, /images\/platforms\/feishu-doc\.svg/);
assert.match(wxml, /images\/platforms\/xhs-note\.svg/);
assert.match(wxml, /images\/platforms\/douyin-video\.svg/);
assert.match(wxml, /images\/platforms\/xhs-video\.svg/);
assert.match(wxml, /images\/platforms\/bilibili-video\.svg/);
assert.match(wxml, /images\/platforms\/xiaoyuzhou-audio\.svg/);
assert.match(wxml, /最近同步/);
assert.match(wxml, /class="recent-section compact"/);
assert.match(wxml, /wx:for="\{\{recentList\}\}"/);
assert.match(wxml, /wx:if="\{\{index < 2\}\}"/);
assert.match(wxml, /class="home-ad-slot"/);
assert.doesNotMatch(wxml, /广告位预留/);
assert.doesNotMatch(wxml, /骞垮憡浣嶉鐣?/);
assert.doesNotMatch(wxml, /bindtap="showMineView"/);
assert.match(wxml, /领取 7 天 Pro 体验/);
assert.match(wxml, /点击后会直接开通 7 天体验，不需要再输入兑换码。/);
assert.match(wxml, /bindtap="claimTrialRedeemCode"/);
assert.match(wxml, /bindtap="copyFormalMembershipWechat"/);
assert.match(wxml, /\{\{trialRedeemCode\}\}/);
assert.match(wxml, /一键复制兑换码/);
assert.match(wxml, /有效期至 \{\{trialRedeemCodeExpiresLabel\}\}/);
assert.match(wxml, /该兑换码已到期，请联系张张续期。/);
assert.doesNotMatch(wxml, /bindtap="navigateToPro">领取 Pro 体验卡/);
assert.match(wxml, /bindtap="copyCurrentRedeemCode"/);
assert.match(wxml, /正在读取当前微信开通 Pro 时使用的兑换码/);
assert.match(wxml, /暂未读取到兑换码记录/);
assert.doesNotMatch(wxml, /当前 Pro 权限不是通过兑换码开通/);
assert.match(wxml, /加入用户群/);
assert.match(wxml, /data-note="OB 群" bindtap="copyWechatWithNote"/);
assert.doesNotMatch(wxml, /联系张张 \/ 加入用户群/);
assert.match(wxml, /bindtap="readClipboard"/);
assert.match(wxml, /bindtap="saveWebpageFromClipboardOrInput"/);
assert.match(wxml, /bindtap="toggleRecording"/);
assert.match(wxml, /bindtap="showImportMaterialSheet"/);
assert.match(wxml, /class="transcription-mode-row/);
assert.match(wxml, /\{\{cloudTranscriptionSummary\}\}/);
assert.match(wxml, /\{\{cloudQuotaSummary\}\}/);
assert.match(wxml, /class="home-capability-strip"/);
assert.match(wxml, /文本、图文链接、本地图文文件/);
assert.match(wxml, /录音、音视频链接、本地MP3文件/);
assert.match(wxml, /open-type="share"/);

assert.match(wxml, /\{\{isBound \? '已绑定 Obsidian' : '1 分钟绑定 Obsidian'\}\}/);
assert.match(wxml, /\{\{displayBindCode\}\}/);
assert.match(wxml, /bindtap="toggleBindCodeVisibility"/);
assert.match(wxml, /bindtap="replaceCode"/);
assert.match(wxml, /class="bind-device-panel white"/);
assert.match(wxml, /bindtap="increaseBindDeviceLimit"/);
assert.match(wxml, /bindtap="confirmUnbindClient"/);
assert.match(wxml, /bindtap="showTutorialModal">详细教程/);
assert.match(wxml, /飞书链接/);
assert.match(wxml, /Pro 开通详细教程/);
assert.match(wxml, /详细教程，飞书链接/);
assert.match(wxml, /1\. 领取 7 天体验/);
assert.match(wxml, /2\. 更新插件为最新版本/);
assert.match(wxml, /3\. 安装本地转写组件即可开始转写音视频/);
assert.match(
  wxml,
  /2\. 更新插件为最新版本[\s\S]*images\/tutorials\/pro-install-local-asr\.png[\s\S]*3\. 安装本地转写组件即可开始转写音视频[\s\S]*images\/tutorials\/pro-update-plugin\.png/,
);
assert.doesNotMatch(wxml, /obsidian绑定与pro开通详细教程/);
assert.doesNotMatch(wxml, /contact-box/);
assert.match(wxml, /wx:if="\{\{announcementVisible\}\}"/);
assert.match(wxml, /class="announcement-sheet"/);
assert.match(wxml, /bindtap="hideAnnouncementSheet"/);
assert.match(wxml, /bindtap="hideAnnouncementAndShowMine"/);
assert.match(wxml, /立即前往/);
assert.doesNotMatch(wxml, /查看 Pro 与帮助/);

assert.match(wxss, /\.tabbar/);
assert.match(wxss, /\.tabbar-item/);
assert.match(wxss, /\.platform-mini-card/);
assert.match(wxss, /\.platform-compact-strip/);
assert.match(wxss, /\.platform-compact-node/);
assert.doesNotMatch(wxss, /\.platform-support-groups/);
assert.doesNotMatch(wxss, /\.platform-support-group/);
assert.doesNotMatch(wxss, /\.platform-compact-row/);
assert.doesNotMatch(wxss, /\.platform-mini-label/);
assert.match(wxss, /\.platform-logo-image/);
assert.match(wxss, /\.recent-section\.compact/);
assert.match(wxss, /\.platform-mini-section \+ \.recent-section/);
assert.match(wxss, /\.home-ad-slot/);
assert.match(wxss, /\.plugin-update-notice/);
assert.match(wxss, /\.notice-action/);
assert.match(wxss, /\.announcement-sheet/);
assert.match(wxss, /\.view-mine/);
assert.match(wxss, /\.benefit-table/);
assert.match(wxss, /\.benefit-table-row/);
assert.match(wxss, /text-align: center/);
assert.match(wxss, /\.capture-actions/);
assert.match(wxss, /\.bind-device-panel/);
assert.match(wxss, /\.usage-status/);
assert.match(wxss, /\.upload-progress-card/);
assert.match(wxss, /\.upload-progress-fill/);

assert.match(js, /ANNOUNCEMENT_VERSION/);
assert.match(js, /DEFAULT_UPDATE_ITEMS/);
assert.match(js, /DEFAULT_PLUGIN_VERSION = '1\.2\.8'/);
assert.match(js, /ANNOUNCEMENT_VERSION = '2026-06-14-local-transcription-first'/);
assert.match(js, /Pro 版，已开启7天全面体验。前往开通 Pro 领取会员和查看教程。/);
assert.match(js, /Pro 版，已开启7天全面体验/);
assert.match(js, /前往开通 Pro 领取会员和查看教程/);
assert.doesNotMatch(js, /优化音视频本地转写/);
assert.doesNotMatch(js, /临时关闭云端转写入口/);
assert.doesNotMatch(js, /修复音视频转写同步问题/);
assert.doesNotMatch(js, /新增 macOS 本地转写组件安装支持/);
assert.doesNotMatch(js, /新增大文件上传进度和插件同步阶段提示/);
assert.doesNotMatch(js, /修复上传进度卡在 0%/);
assert.doesNotMatch(js, /识别旧版本地转写脚本/);
assert.doesNotMatch(js, /修复 Windows 缺少 VC\+\+ 运行库/);
assert.match(js, /DEFAULT_PLUGIN_UPDATED_AT = '2026-06-14'/);
assert.match(js, /pluginVersion: DEFAULT_PLUGIN_VERSION/);
assert.match(js, /pluginUpdatedAt: DEFAULT_PLUGIN_UPDATED_AT/);
assert.match(js, /usageStatusText: buildUsageStatusText/);
assert.match(js, /loadDailyUsageStatus/);
assert.match(js, /Pro 使用中，今日不限次数/);
assert.match(js, /showLaunchAnnouncementIfNeeded/);
assert.match(js, /announcement_seen_/);
assert.match(js, /isLatestAnnouncementConfig/);
assert.match(js, /config\.announcementVersion === ANNOUNCEMENT_VERSION/);
assert.match(js, /tutorialUrl: TUTORIAL_URL/);
assert.match(js, /currentView: 'bind'/);
assert.match(js, /DEFAULT_INPUT_PLACEHOLDER = '复制编辑文字，网页链接请点击读取网页链接'/);
assert.doesNotMatch(js, /粘贴文字、链接，或录一段语音/);
assert.match(js, /alreadyRedeemed \? '该兑换码已激活过' : '兑换成功'/);
assert.match(js, /handleMembershipPrimary/);
assert.match(js, /copyCurrentRedeemCode/);
assert.match(js, /暂未读取到兑换码记录/);
assert.doesNotMatch(js, /当前 Pro 不是兑换码开通/);
assert.match(js, /switchMainTab/);
assert.match(js, /showCollectView/);
assert.match(js, /showMineView/);
assert.match(js, /copyContactWechat/);
assert.match(js, /copyWechatWithNote/);
assert.match(js, /copyFormalMembershipWechat/);
assert.match(js, /开通正式会员/);
assert.match(js, /可免费领取 7 天 Pro 试用/);
assert.match(js, /微信已复制，添加备注/);
assert.match(js, /ob用户群/);
assert.match(js, /announcementVisible: true/);
assert.match(js, /hideAnnouncementSheet/);
assert.match(js, /hideAnnouncementAndShowMine/);
assert.match(js, /buildMembershipCard/);
assert.match(js, /loadEntitlementStatus/);
assert.match(js, /membershipCard: buildMembershipCard/);
assert.match(js, /wx\.showShareMenu/);
assert.match(js, /REWARDED_AD_UNIT_ID/);
assert.match(js, /quotaUnlockPending: false/);
assert.match(js, /quotaUnlockVisible: false/);
assert.match(js, /unlockDailyUsageByShare/);
assert.match(js, /unlockDailyUsageByAd/);
assert.match(js, /MAX_CHAT_UPLOAD_COUNT\s*=\s*10/);
assert.match(js, /MAX_ALBUM_UPLOAD_COUNT\s*=\s*9/);
assert.match(js, /SUPPORTED_CHAT_UPLOAD_EXTENSIONS/);
assert.match(js, /showImportMaterialSheet/);
assert.match(js, /wx\.showActionSheet/);
assert.match(js, /CLOUD_TRANSCRIPTION_STORAGE_KEY/);
assert.match(js, /CLOUD_TRANSCRIPTION_TEMP_DISABLED = true/);
assert.match(js, /resolveCloudTranscriptionChoice/);
assert.match(js, /buildCloudTranscriptionPayload\('local', 'cloud-disabled'\)/);
assert.match(wxml, /wx:if="\{\{false\}\}" class="transcription-mode-row/);
assert.match(js, /: 'local';\s*return \{\s*defaultMode/s);
assert.doesNotMatch(js, /shouldMigrateOldLocalDefault/);
assert.doesNotMatch(js, /CLOUD_TRANSCRIPTION_PREFERENCE_VERSION/);
assert.match(js, /cloudRemainingSeconds/);
assert.match(js, /quota-exhausted/);
assert.match(js, /isAudioVideoWebpageUrl/);
assert.match(js, /webpageMediaType: 'audio_video'/);
assert.match(js, /ensureProAccessForTranscription/);
assert.match(js, /录音转写需要 Pro/);
assert.match(js, /音频文件转写需要 Pro/);
assert.match(js, /音视频链接需要 Pro/);
assert.match(js, /selectedFiles\.some\(isAudioInboxFile\)/);
assert.match(js, /cloudQuotaSummary/);
assert.match(js, /cloudPreTranscription/);
assert.match(js, /CLOUD_PRE_TRANSCRIPTION_RETRY_DELAYS_MS/);
assert.match(js, /startCloudPreTranscriptionWithRetry/);
assert.match(js, /if \(CLOUD_TRANSCRIPTION_TEMP_DISABLED\) return;/);
assert.match(js, /waitMs/);
assert.match(js, /speakerDiarization: useCloud/);
assert.match(js, /rememberCloudTranscriptionChoice/);
assert.match(js, /uploadProgressVisible: false/);
assert.match(js, /setUploadProgress/);
assert.match(js, /resetUploadProgress/);
assert.match(js, /chooseAlbumMedia/);
assert.match(js, /wx\.chooseMedia/);
assert.match(inboxServiceJs, /onProgressUpdate/);
assert.match(inboxServiceJs, /uploadWithProgress/);
assert.match(inboxServiceJs, /success: resolve/);
assert.match(inboxServiceJs, /fail: reject/);
assert.match(js, /saveInboxFiles\(files\)/);
assert.match(js, /saveOneInboxFile\(file\)/);
assert.match(js, /handleForwardMaterials/);
assert.match(js, /getForwardMaterialFile/);
assert.match(js, /saveWebpageUrl\(url, sourceText\)/);
const saveWebpageUrlBody = js.slice(
  js.indexOf('async saveWebpageUrl'),
  js.indexOf('showImportMaterialSheet'),
);
assert.match(saveWebpageUrlBody, /this\.triggerCloudPreTranscriptionIfQueued\(response\.result\.data\)/);
const handleSaveBody = js.slice(
  js.indexOf('async handleSave'),
  js.indexOf('triggerCloudPreTranscriptionIfQueued', js.indexOf('async handleSave')),
);
assert.match(handleSaveBody, /extractHttpUrl\(content\)/);
assert.match(handleSaveBody, /classifyContent\(content\) === 'WEBPAGE'/);
assert.match(handleSaveBody, /await this\.saveWebpageUrl\(url, content\)/);
assert.match(js, /requestBindStatus/);
assert.match(js, /startBindStatusPolling/);
assert.match(js, /requestBindCode\(\{ switchToCollectIfBound: true \}\)/);
assert.match(js, /trackAnalyticsOnce\('app_visit'\)/);
assert.match(js, /trackAnalyticsOnce\('bind_page_view'\)/);
assert.match(js, /trackAnalyticsEvent/);

assert.match(proWxml, /领取 7 天 Pro 体验/);
assert.match(proWxml, /购买 Pro 正式版/);
assert.match(proWxml, /Pro 月卡/);
assert.match(proWxml, /Pro 年卡/);
assert.match(proWxml, /bindtap="createFormalPaymentOrder"/);
assert.match(proWxml, /点击后会直接开通 7 天体验/);
assert.match(proWxml, /\{\{trialRedeemCode\}\}/);
assert.match(proWxml, /bindtap="claimTrialRedeemCode"/);
assert.match(proWxml, /bindtap="copyFormalMembershipWechat"/);
assert.match(proWxml, /bindtap="copyTrialRedeemCode"/);
assert.doesNotMatch(proWxml, /bindtap="useTrialRedeemCode"/);
assert.match(proWxml, /有效期至/);
assert.match(proWxml, /该兑换码已到期，请联系张张续期/);
assert.doesNotMatch(proWxml, /兑换码仅作为开通凭证和售后查询使用/);
assert.match(proWxml, /class="benefit-table"/);
assert.match(proWxml, /class="benefit-table-header"/);
assert.match(proWxml, /class="benefit-table-row"/);
assert.match(proWxml, /权益/);
assert.match(proWxml, /使用次数/);
assert.match(proWxml, /5次\/天/);
assert.match(proWxml, /不限/);
assert.match(proWxml, /Pro 开通详细教程/);
assert.match(proWxml, /bindtap="copyProTutorialLink"/);
assert.match(proWxml, /1\. 领取 7 天体验/);
assert.match(proWxml, /2\. 更新插件为最新版本/);
assert.match(proWxml, /3\. 安装本地转写组件即可开始转写音视频/);
assert.match(
  proWxml,
  /2\. 更新插件为最新版本[\s\S]*images\/tutorials\/pro-install-local-asr\.png[\s\S]*3\. 安装本地转写组件即可开始转写音视频[\s\S]*images\/tutorials\/pro-update-plugin\.png/,
);
assert.match(proWxml, /详细教程，飞书链接/);
assert.match(proWxml, /bindtap="copyUserGroupWechat"/);
assert.match(proWxml, /OB 群/);
assert.doesNotMatch(proWxml, /联系张张领取试用码/);
assert.doesNotMatch(proWxml, /填入下方兑换码/);
assert.doesNotMatch(proWxml, /暂未读取到兑换码记录/);
assert.doesNotMatch(proWxml, /bindtap="copyCurrentRedeemCode"/);
assert.doesNotMatch(proWxml, /已有兑换码/);
assert.doesNotMatch(proWxml, /请输入兑换码/);
assert.match(proWxml, /免费版/);
assert.match(proWxml, /Pro版/);
assert.match(proWxml, /文字、文件转写/);
assert.match(proWxml, /语音、MP3转写/);
assert.match(proWxml, /语音、MP3转写[\s\S]*<view class="benefit-cell">×<\/view>[\s\S]*<view class="benefit-cell pro-col">√<\/view>/);
assert.match(proWxml, /图文链接转写/);
assert.match(proWxml, /音视频链接转写/);
assert.doesNotMatch(proWxml, /需用户充值配API/);
assert.doesNotMatch(proWxml, /无需配API/);
assert.doesNotMatch(proWxml, /云端额度：已用 \{\{cloudQuota.usedText\}\} \/ 总 \{\{cloudQuota.totalText\}\}/);
assert.doesNotMatch(proWxml, /保存音视频时选择云端转写/);
assert.doesNotMatch(proWxml, /heyhmjx|\{\{contactWechat\}\}/);
assert.doesNotMatch(proJs, /redeemAccessCode/);
assert.match(proJs, /getTrialRedeemCode/);
assert.match(proJs, /createPaymentOrder/);
assert.match(proJs, /createFormalPaymentOrder/);
assert.match(proJs, /selectedPaymentPlanId/);
assert.match(proJs, /claimTrialRedeemCode/);
assert.match(proJs, /copyTrialRedeemCode/);
assert.doesNotMatch(proJs, /useTrialRedeemCode/);
assert.match(proJs, /trialRedeemCodeExpiresAt/);
assert.match(proJs, /trialRedeemCodeExpired/);
assert.match(proJs, /copyProTutorialLink/);
assert.match(proJs, /copyUserGroupWechat/);
assert.match(proJs, /copyFormalMembershipWechat/);
assert.match(proJs, /开通正式会员/);
assert.match(proJs, /OB 群/);
assert.match(proJs, /FUNCTIONS_TIME_LIMIT_EXCEEDED/);
assert.match(proJs, /Lm5kw8QXdiQE96kaDUYcnIsVnAd/);
assert.match(proJs, /getEntitlementStatus/);
assert.doesNotMatch(proJs, /copyCurrentRedeemCode/);
assert.doesNotMatch(proJs, /暂未读取到兑换码记录/);
assert.match(proJs, /CONTACT_WECHAT = 'heyhmjx'/);
assert.match(proJs, /formatCloudMinutes/);
assert.match(proJs, /buildCloudQuota/);
assert.match(proJs, /refreshEntitlementStatus/);
assert.match(proJs, /quotaRefreshing/);
assert.match(proJs, /cloudQuotaSeconds/);
assert.match(proJs, /cloudRemainingSeconds/);
assert.match(proJs, /entitlementStatusLoading/);
assert.match(proJs, /entitlementStatusLoaded/);
assert.doesNotMatch(proJs, /onShow\(\)\s*\{\s*if \(this\.inboxService\) \{\s*this\.loadEntitlementStatus\(\);/s);

assert.match(helpWxml, /绑定 Obsidian 教程/);
assert.match(helpWxml, /WeChat Inbox Sync/);
assert.match(helpWxml, /复制教程链接/);
assert.match(helpWxml, /复制微信号/);
assert.match(helpWxml, /ob会员 \/ ob试用/);
assert.match(helpJs, /CONTACT_WECHAT = 'heyhmjx'/);
assert.match(helpJs, /Lm5kw8QXdiQE96kaDUYcnIsVnAd/);
assert.match(helpJs, /copyTutorialLink/);
assert.match(helpJs, /copyWechat/);

assert.match(appJs, /forwardMaterials/);
assert.match(appJs, /scene\s*===\s*1173/);
assert.match(appJs, /consumeForwardMaterials/);
