'use strict';
const assert=require('node:assert/strict'),Module=require('module'),fs=require('fs'),path=require('path'),os=require('os'),crypto=require('crypto');
const original=Module._load;
Module._load=function(name,...args){if(name==='obsidian')return {Plugin:class{},Modal:class{},PluginSettingTab:class{},Setting:class{},Notice:class{},requestUrl:async()=>{throw Error('unexpected network');}};return original.call(this,name,...args);};
const Plugin=require('../obsidian-plugin/wechat-inbox-sync/main');Module._load=original;
const h=require('../obsidian-plugin/wechat-inbox-sync/src/local-douyin-resolver-utils');
const bytes=Buffer.from('synthetic resolver binary'),sha=crypto.createHash('sha256').update(bytes).digest('hex');
const asset={source:'cloudbase',url:'https://example.invalid/resolver',sha256:sha,byteLength:bytes.length,version:'fixture-1'};
let checks=0;
function fixture(mask=0){const p=new Plugin();p.settings=Plugin.__test.mergeSettings({});p.ensureProFeatureAccess=async()=>({hasAccess:true});p.showLocalComponentInstallFailure=async()=>{};const ready={asr:!!(mask&1),ocr:!!(mask&2),resolver:!!(mask&4)},calls=[];
 p.getLocalTranscriptionComponentReadiness=()=>({ready:Object.values(ready).every(Boolean),asrStatus:{ready:ready.asr},ocrStatus:{ready:ready.ocr},resolverStatus:{ready:ready.resolver}});
 for(const [method,key] of [['installLocalAsr','asr'],['installLocalOcr','ocr'],['ensureLocalDouyinResolver','resolver']])p[method]=async()=>{calls.push(key);ready[key]=true;};return {p,ready,calls};}
function resolverFixture(root,platform='win32') {const p=new Plugin();p.settings=Plugin.__test.mergeSettings({});p.ensureProFeatureAccess=async()=>({hasAccess:true});p.getConfiguredLocalAsrPlatform=()=>platform;p.getLocalDouyinResolverRoot=()=>root;p.getAuthorizedLocalComponentManifest=async()=>({version:asset.version,assets:[{...asset,id:'resolver',downloadUrl:asset.url}]});p.downloadLocalDouyinResolverAsset=async()=>bytes;p.getOfficialLocalDouyinResolverManifest=async()=>{throw Error('unexpected official fallback');};return p;}
async function run(){
 for(let mask=0;mask<8;mask++){const {p,ready,calls}=fixture(mask);await p.installLocalTranscriptionComponents({allComponents:true});assert.ok(Object.values(ready).every(Boolean));assert.deepEqual(calls,['asr','ocr','resolver'].filter((_,i)=>!(mask&(1<<i))));checks++;}
 for(const failed of ['asr','ocr','resolver']){const {p,ready,calls}=fixture();let fail=true;const methods={asr:'installLocalAsr',ocr:'installLocalOcr',resolver:'ensureLocalDouyinResolver'};p[methods[failed]]=async()=>{calls.push(failed);if(fail)throw Error('synthetic failure');ready[failed]=true;};await assert.rejects(p.installLocalTranscriptionComponents({requireAsr:true}),/已成功准备的组件会保留/);assert.equal(calls.length,3);calls.length=0;fail=false;await p.installLocalTranscriptionComponents({allComponents:true});assert.deepEqual(calls,[failed]);checks++;}
 {const {p,calls}=fixture();await Promise.all([p.installLocalTranscriptionComponents({allComponents:true}),p.installLocalTranscriptionComponents({allComponents:true})]);assert.equal(calls.length,3);checks++;}
 for(const status of [401,403,429]){const {p,calls}=fixture();p.installLocalAsr=async()=>{throw Object.assign(Error('denied'),{status});};await assert.rejects(p.installLocalTranscriptionComponents({allComponents:true}));assert.deepEqual(calls,[]);checks++;}
 {let fallback=0;const stages=[];const result=await h.downloadVerifiedResolverAsset(asset,{download:async()=>{throw Object.assign(Error('TLS bad https://private.invalid?secret=x'),{code:'UNABLE_TO_VERIFY_LEAF_SIGNATURE'});},systemDownload:async()=>{fallback++;return bytes;},onStage:e=>stages.push(e)});assert.deepEqual(result,bytes);assert.equal(fallback,1);assert.ok(stages.some(e=>e.code==='UNABLE_TO_VERIFY_LEAF_SIGNATURE'));assert.ok(!JSON.stringify(stages).includes('secret'));checks++;}
 {let fallback=0;await assert.rejects(h.downloadVerifiedResolverAsset({...asset,sha256:'0'.repeat(64)},{download:async()=>bytes,systemDownload:async()=>{fallback++;return bytes;}}),e=>e.code==='HASH_MISMATCH');assert.equal(fallback,0);checks++;}

 for(const status of [401,403,429]){let called=false;await assert.rejects(h.downloadVerifiedResolverAsset(asset,{download:async()=>{throw Object.assign(Error('denied'),{status});},systemDownload:async()=>{called=true;return bytes;}}),e=>e.status===status);assert.equal(called,false);checks++;}
 {const {p,calls}=fixture(7);let forced;p.ensureLocalDouyinResolver=async opts=>{forced=opts.force;calls.push('resolver');};const readiness=p.getLocalTranscriptionComponentReadiness(),plan=Plugin.__test.buildLocalComponentRefreshPlan(readiness,{includeOptionalUpdates:true,resolverUpdateAvailable:true});assert.equal(plan.forceResolver,true);await p.installLocalTranscriptionComponents(plan);assert.deepEqual(calls,['resolver']);assert.equal(forced,true);assert.equal(Plugin.__test.buildLocalComponentRefreshPlan(readiness).requireResolver,false);assert.equal(Plugin.__test.buildLocalComponentRefreshPlan({...readiness,ocrStatus:{ready:false}},{checkResolverUpdates:true}).forceResolver,false);checks++;}

 // Exercise the real system transport's curl flags and HTTP denial mapping without network.
 for(const status of [401,403,429]){let flags;const original=Module._load;Module._load=function(name,...args){if(name==='child_process')return {execFile:(command,args,options,callback)=>{flags=args;assert.equal(options.windowsHide,true);queueMicrotask(()=>callback(Object.assign(Error('HTTP failure'),{code:22}),String(status)));}};return original.call(this,name,...args);};let transport;try{const filename=require.resolve('../obsidian-plugin/wechat-inbox-sync/src/local-douyin-resolver-utils');const loaded=new Module(filename,module);loaded.filename=filename;loaded.paths=Module._nodeModulePaths(path.dirname(filename));loaded._compile(fs.readFileSync(filename,'utf8'),filename);transport=loaded.exports;}finally{Module._load=original;}await assert.rejects(transport.downloadResolverViaSystem(asset.url),e=>e.status===status);assert.equal(flags.includes('--insecure'),false);assert.equal(flags.includes('-k'),false);assert.equal(flags[flags.indexOf('--proto-redir')+1],'=https');checks++;}
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'unified-components-test-'));
 try{
  for(const platform of ['win32','darwin']){const dir=path.join(root,platform),p=resolverFixture(dir,platform);const first=await p.ensureLocalDouyinResolver();assert.equal(first.updated,true);assert.equal(p.getLocalDouyinResolverInstallStatus().ready,true);let downloads=0;p.downloadLocalDouyinResolverAsset=async()=>{downloads++;return bytes;};p.getAuthorizedLocalComponentManifest=async()=>{throw Error('healthy cache must not query manifest');};assert.equal((await p.ensureLocalDouyinResolver()).source,'verified-cache');assert.equal(downloads,0);
   fs.writeFileSync(first.executablePath,'broken');assert.equal(p.getLocalDouyinResolverInstallStatus().ready,false);p.getAuthorizedLocalComponentManifest=async()=>({version:asset.version,assets:[{...asset,id:'resolver',downloadUrl:asset.url}]});await p.ensureLocalDouyinResolver();assert.equal(downloads,1);assert.equal(p.getLocalDouyinResolverInstallStatus().ready,true);
   p.getAuthorizedLocalComponentManifest=async()=>{throw Object.assign(Error('denied'),{status:403,code:'PRO_REQUIRED'});};await assert.rejects(p.ensureLocalDouyinResolver({force:true}),e=>e.code==='PRO_REQUIRED');assert.equal(p.getLocalDouyinResolverInstallStatus().ready,true);checks++;
  }

  {const p=resolverFixture(path.join(root,'update'));const first=await p.ensureLocalDouyinResolver();let downloads=0;p.downloadLocalDouyinResolverAsset=async()=>{downloads++;return bytes;};await p.ensureLocalDouyinResolver({force:true});assert.equal(downloads,0,'same hash must reuse bytes');const updated=Buffer.from('new synthetic resolver binary'),digest=crypto.createHash('sha256').update(updated).digest('hex');p.getAuthorizedLocalComponentManifest=async()=>({version:'fixture-2',assets:[{id:'resolver',downloadUrl:asset.url,sha256:digest,byteLength:updated.length}]});p.downloadLocalDouyinResolverAsset=async()=>{downloads++;return updated;};await p.ensureLocalDouyinResolver({force:true});assert.equal(downloads,1);assert.deepEqual(fs.readFileSync(first.executablePath),updated);assert.equal(p.getLocalDouyinResolverInstallStatus().version,'fixture-2');p.getAuthorizedLocalComponentManifest=async()=>{throw Error('synthetic network failure');};await assert.rejects(p.ensureLocalDouyinResolver({force:true}));assert.deepEqual(fs.readFileSync(first.executablePath),updated);assert.equal(p.getLocalDouyinResolverInstallStatus().ready,true);checks++;}
  for(const status of [401,403,429]){const p=resolverFixture(path.join(root,'binary-deny-'+status));p.downloadLocalDouyinResolverAsset=async()=>{throw Object.assign(Error('denied'),{status});};await assert.rejects(p.ensureLocalDouyinResolver(),e=>e.status===status);assert.equal(p.getLocalDouyinResolverInstallStatus().ready,false);checks++;}
  {const dir=path.join(root,'rollback'),target=path.join(dir,'yt-dlp.exe');h.commitVerifiedResolver(target,bytes,asset,'win32','x64');const rename=fs.renameSync;fs.renameSync=(from,to)=>{if(to===target+'.verified.json')throw Object.assign(Error('read-only receipt'),{code:'EACCES'});return rename(from,to);};try{await assert.rejects(async()=>h.commitVerifiedResolver(target,Buffer.from('new'),{...asset,sha256:crypto.createHash('sha256').update('new').digest('hex')},'win32','x64'));}finally{fs.renameSync=rename;}assert.deepEqual(fs.readFileSync(target),bytes);assert.equal(h.getVerifiedResolverStatus(target,'win32','x64').ready,true);checks++;}
  {const p=resolverFixture(path.join(root,'fallback'));let official=0;p.getAuthorizedLocalComponentManifest=async()=>null;p.getOfficialLocalDouyinResolverManifest=async()=>{official++;return {manifest:{schemaVersion:1,version:'fixture-2',assets:{'win32-x64':{url:asset.url,sha256:sha}}}};};await p.ensureLocalDouyinResolver();assert.equal(official,1);assert.ok(p.getLocalDouyinResolverInstallDiagnostic().some(e=>e.source==='cloudbase'&&e.status==='failed'));assert.ok(p.getLocalDouyinResolverInstallDiagnostic().some(e=>e.source==='github'&&e.status==='complete'));checks++;}
  {const p=resolverFixture(path.join(root,'binary-fallback'));let attempts=[];p.downloadLocalDouyinResolverAsset=async a=>{attempts.push(a.source);if(a.source==='cloudbase')throw Object.assign(Error('temporary'),{code:'ECONNRESET'});return bytes;};p.getOfficialLocalDouyinResolverManifest=async()=>({manifest:{schemaVersion:1,version:'fixture-3',assets:{'win32-x64':{url:asset.url,sha256:sha}}}});await p.ensureLocalDouyinResolver();assert.deepEqual(attempts,['cloudbase','github']);checks++;}
  {const p=resolverFixture(path.join(root,'legacy'));fs.mkdirSync(p.getLocalDouyinResolverRoot(),{recursive:true});const target=path.join(p.getLocalDouyinResolverRoot(),'yt-dlp.exe');fs.writeFileSync(target,bytes);assert.equal(p.getInstalledLocalDouyinResolver(),null);p.downloadLocalDouyinResolverAsset=async()=>{throw Error('same verified bytes should be reused');};await p.ensureLocalDouyinResolver();assert.equal(p.getLocalDouyinResolverInstallStatus().ready,true);checks++;}
  for(const error of [{status:401},{status:403},{status:429},{code:'COMPONENT_CLIENT_UPGRADE_REQUIRED'},{code:'COMPONENT_DOWNLOAD_RATE_LIMITED'}]){const p=resolverFixture(path.join(root,'deny'));p.getAuthorizedLocalComponentManifest=async()=>{throw Object.assign(Error('synthetic denial'),error);};p.getOfficialLocalDouyinResolverManifest=async()=>{throw Error('must not call official');};await assert.rejects(p.ensureLocalDouyinResolver(),e=>e.status===error.status&&e.code===error.code);checks++;}
  {const p=resolverFixture(path.join(root,'bad-hash'));p.downloadLocalDouyinResolverAsset=async()=>Buffer.from('tampered');await assert.rejects(p.ensureLocalDouyinResolver(),e=>e.code==='HASH_MISMATCH');assert.equal(p.getInstalledLocalDouyinResolver(),null);checks++;}
 }finally {if(path.dirname(path.resolve(root))!==path.resolve(os.tmpdir()))throw Error('unsafe cleanup path');fs.rmSync(root,{recursive:true,force:true});}
 // Pro denial must also stay closed inside the authorized-manifest helper.
 for(const status of [401,403,429]){const p=new Plugin();p.getConfiguredLocalAsrPlatform=()=> 'win32';p.ensureProFeatureAccess=async()=>({hasAccess:true});p.getActiveBindings=()=>[{token:'synthetic'}];p.requestJson=async()=>{throw Object.assign(Error('denied'),{status});};await assert.rejects(p.getAuthorizedLocalComponentManifest('douyin'),e=>e.status===status);checks++;}
 console.log('Unified component behavioral checks passed: '+checks);
}
run().catch(e=>{console.error(e);process.exitCode=1;});
